apiVersion: apps/v1
kind: Deployment

metadata:
  name: soap-generation-service

spec:
  selector:
    matchLabels:
      app: soap-generation-service

  template:

    metadata:
      labels:
        app: soap-generation-service

    spec:

      containers:

      - name: soap-generation-service

        image: soap-generation-service:v1

        imagePullPolicy: Always

        envFrom:
        - configMapRef:
            name: soap-generation-config

        ports:
        - containerPort: 8080
        - containerPort: 9100

        resources:
          requests:
            cpu: 250m
            memory: 256Mi

          limits:
            cpu: 1000m
            memory: 512Mi


      - name: ollama

        image: ollama/ollama:latest

        ports:
        - containerPort: 11434

        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama

        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"

          limits:
            cpu: "2000m"
            memory: "3Gi"

      volumes:

      - name: ollama-storage
        emptyDir: {}